export const images = {
  logo: "/images/spherearth-logo.png",
  homepageHero: "/images/homepage-hero-banner.png",
  whyWeExist: "/images/why-we-exist-image.png",
  fourPillars: "/images/four-pillars-section-image.png",
  globalVision: "/images/global-vision-map-placement-built-in-toronto-designed-for-the-world-image.png",
  programCard: "/images/homepage-service-card-image.png",
  families: "/images/families-section-image.png",
  scholarship: "/images/scholarship-section-image.png",
  sponsorship: "/images/sponsorship-section-image.png",
  becomeASponsor: "/images/become-a-sponsor.png",
  programsHero: "/images/programs-header-image.png",
  admissionsHero: "/images/admissions-header-image.jpg",
  verifyRepresentative: "/images/verify-representative-page-image.png",
  fraudPrevention: "/images/fraud-prevention-page-image.png",
  footballGlobe: "/images/football-globe-image.png",
  mapleLeaf: "/images/maple-leaf-football-emblem-image.png",
  stadiumTunnel: "/images/stadium-tunnel-image.png",
  torontoReflection: "/images/toronto-reflection-ball-image.png",
  passportBoots: "/images/passport-football-boots-image.png",
} as const;
