export const images = {
  logo: "/images/spherearth-logo.webp",
  homepageHero: "/images/homepage-hero-banner.webp",
  whyWeExist: "/images/why-we-exist-image.webp",
  families: "/images/families-section-image.webp",
  sponsorship: "/images/sponsorship-section-image.webp",
  becomeASponsor: "/images/become-a-sponsor.webp",
  becomeAnAdvisor: "/images/become-an-advisor.webp",
  programsHero: "/images/programs-hero.webp",
  faqHero: "/images/faq.webp",
  rolesHero: "/images/roles-hero.webp",
  careersHero: "/images/career-hero.webp",
  successStoriesHero: "/images/success-story-hero.webp",
  enquiryHero: "/images/enquiry-hero.webp",
  admissionsHero: "/images/admissions-header-image.webp",
  verifyRepresentative: "/images/verify-representative-page-image.webp",
  fraudPrevention: "/images/fraud-prevention-page-image.webp",
  stadiumTunnel: "/images/stadium-tunnel-image.webp",
  torontoReflection: "/images/toronto-reflection-ball-image.webp",
} as const;
